In [23]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import pandas as pd
import csv
import janitor
import numpy as np

In [24]:
silva = pd.read_csv("arb-silva.de_testprime_taxlist_848715.csv", sep = ";")

In [26]:
silva

,job_name,taxonomy,coverage,specificity,accessions,eligible,match,mismatch,nodata,outgroup_matchable,outgroup_matched
0,NaN,SILVA (only NR);Unclassified;,0.0,0.0,0,0,0,0,0,457210,383583
1,NaN,SILVA (only NR);Archaea;,81.0,16.0,20197,19976,16171,3805,221,437234,367412
2,NaN,SILVA (only NR);Archaea;Aenigmarchaeota;,3.5,16.0,319,313,11,302,6,456897,383572
3,NaN,SILVA (only NR);Archaea;Aenigmarchaeota;Aenigm...,2.6,16.1,161,155,4,151,6,457055,383579
4,NaN,SILVA (only NR);Archaea;Aenigmarchaeota;Aenigm...,2.6,16.1,161,155,4,151,6,457055,383579
5,NaN,SILVA (only NR);Archaea;Aenigmarchaeota;Aenigm...,0.0,0.0,16,16,0,16,0,457194,383583
6,NaN,SILVA (only NR);Archaea;Aenigmarchaeota;Deep S...,3.9,16.1,155,155,6,149,0,457055,383577
7,NaN,SILVA (only NR);Archaea;Altiarchaeota;,7.5,16.1,41,40,3,37,1,457170,383580
8,NaN,SILVA (only NR);Archaea;Altiarchaeota;Altiarch...,7.5,16.1,41,40,3,37,1,457170,383580
9,NaN,SILVA (only NR);Archaea;Altiarchaeota;Altiarch...,7.5,16.1,41,40,3,37,1,457170,383580
10,NaN,SILVA (only NR);Archaea;Altiarchaeota;Altiarch...,7.5,16.1,41,40,3,37,1,457170,383580
11,NaN,SILVA (only NR);Archaea;Altiarchaeota;Altiarch...,7.5,16.1,41,40,3,37,1,457170,383580
12,NaN,SILVA (only NR);Archaea;Asgardarchaeota;,86.2,16.1,670,661,570,91,9,456549,383013
13,NaN,SILVA (only NR);Archaea;Asgardarchaeota;Heimda...,90.7,16.1,45,43,39,4,2,457167,383544
14,NaN,SILVA (only NR);Archaea;Asgardarchaeota;Lokiar...,87.0,16.1,527,524,456,68,3,456686,383127
15,NaN,SILVA (only NR);Archaea;Asgardarchaeota;Odinar...,79.1,16.1,95,91,72,19,4,457119,383511
16,NaN,SILVA (only NR);Archaea;Crenarchaeota;,83.4,16.1,7625,7547,6295,1252,78,449663,377288
17,NaN,SILVA (only NR);Archaea;Crenarchaeota;Bathyarc...,83.4,16.1,3641,3600,3001,599,41,453610,380582
18,NaN,SILVA (only NR);Archaea;Crenarchaeota;Methanom...,88.2,16.1,34,34,30,4,0,457176,383553
19,NaN,SILVA (only NR);Archaea;Crenarchaeota;Methanom...,88.2,16.1,34,34,30,4,0,457176,383553
20,NaN,SILVA (only NR);Archaea;Crenarchaeota;Methanom...,88.2,16.1,34,34,30,4,0,457176,383553
21,NaN,SILVA (only NR);Archaea;Crenarchaeota;Methanom...,85.7,16.1,28,28,24,4,0,457182,383559
22,NaN,SILVA (only NR);Archaea;Crenarchaeota;Nitrosos...,82.5,16.1,3259,3224,2659,565,35,453986,380924
23,NaN,SILVA (only NR);Archaea;Crenarchaeota;Nitrosos...,78.8,16.1,170,170,134,36,0,457040,383449
24,NaN,SILVA (only NR);Archaea;Crenarchaeota;Nitrosos...,87.9,16.1,58,58,51,7,0,457152,383532
25,NaN,SILVA (only NR);Archaea;Crenarchaeota;Nitrosos...,87.9,16.1,58,58,51,7,0,457152,383532
26,NaN,SILVA (only NR);Archaea;Crenarchaeota;Nitrosos...,65.2,16.1,66,66,43,23,0,457144,383540
27,NaN,SILVA (only NR);Archaea;Crenarchaeota;Nitrosos...,87.0,16.1,46,46,40,6,0,457164,383543
28,NaN,SILVA (only NR);Archaea;Crenarchaeota;Nitrosos...,48.9,16.1,233,231,113,118,2,456979,383470
29,NaN,SILVA (only NR);Archaea;Crenarchaeota;Nitrosos...,89.1,16.1,131,128,114,14,3,457082,383469
...,...,...,...,...,...,...,...,...,...,...,...
10231,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Oc...,100.0,16.1,2,2,2,0,0,457208,383581
10232,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Oc...,100.0,16.1,3,3,3,0,0,457207,383580
10233,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Oc...,100.0,16.1,3,3,3,0,0,457207,383580
10234,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Oc...,100.0,16.1,1,1,1,0,0,457209,383582
10235,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Oc...,100.0,16.1,2,2,2,0,0,457208,383581
10236,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Oc...,100.0,16.1,2,2,2,0,0,457208,383581
10237,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Oc...,100.0,16.1,2,2,2,0,0,457208,383581
10238,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Op...,20.0,16.1,5,5,1,4,0,457205,383582
10239,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...,87.6,16.1,177,169,148,21,8,457041,383435
10240,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...,100.0,16.1,2,2,2,0,0,457208,383581
10241,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...,83.3,16.1,6,6,5,1,0,457204,383578
10242,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...,100.0,16.1,4,4,4,0,0,457206,383579
10243,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...,100.0,16.1,2,2,2,0,0,457208,383581
10244,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...,100.0,16.1,7,7,7,0,0,457203,383576
10245,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...,100.0,16.1,5,5,5,0,0,457205,383578
10246,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...,100.0,16.1,4,4,4,0,0,457206,383579
10247,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...,100.0,16.1,2,2,2,0,0,457208,383581
10248,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...,80.0,16.1,5,5,4,1,0,457205,383579
10249,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...,78.8,16.1,52,52,41,11,0,457158,383542
10250,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...,66.7,16.1,3,3,2,1,0,457207,383581
10251,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...,100.0,16.1,23,23,23,0,0,457187,383560
10252,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...,100.0,16.1,2,2,2,0,0,457208,383581
10253,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...,70.6,16.1,25,17,12,5,8,457193,383571
10254,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pl...,100.0,16.1,9,9,9,0,0,457201,383574
10255,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pl...,100.0,16.1,2,2,2,0,0,457208,383581
10256,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pl...,100.0,16.1,3,3,3,0,0,457207,383580
10257,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pl...,100.0,16.1,2,2,2,0,0,457208,383581
10258,NaN,SILVA (only NR);Eukaryota;SAR;Stramenopiles;un...,100.0,16.1,12,10,10,0,2,457200,383573
10259,NaN,SILVA (only NR);Eukaryota;uncultured;,81.8,16.1,11,11,9,2,0,457199,383574
10260,NaN,SILVA (only NR);,83.9,100.0,458695,457358,383719,73639,1337,0,0

In [28]:
silva["taxonomy"]

0                            SILVA (only NR);Unclassified;
1                                 SILVA (only NR);Archaea;
2                 SILVA (only NR);Archaea;Aenigmarchaeota;
3        SILVA (only NR);Archaea;Aenigmarchaeota;Aenigm...
4        SILVA (only NR);Archaea;Aenigmarchaeota;Aenigm...
5        SILVA (only NR);Archaea;Aenigmarchaeota;Aenigm...
6        SILVA (only NR);Archaea;Aenigmarchaeota;Deep S...
7                   SILVA (only NR);Archaea;Altiarchaeota;
8        SILVA (only NR);Archaea;Altiarchaeota;Altiarch...
9        SILVA (only NR);Archaea;Altiarchaeota;Altiarch...
10       SILVA (only NR);Archaea;Altiarchaeota;Altiarch...
11       SILVA (only NR);Archaea;Altiarchaeota;Altiarch...
12                SILVA (only NR);Archaea;Asgardarchaeota;
13       SILVA (only NR);Archaea;Asgardarchaeota;Heimda...
14       SILVA (only NR);Archaea;Asgardarchaeota;Lokiar...
15       SILVA (only NR);Archaea;Asgardarchaeota;Odinar...
16                  SILVA (only NR);Archaea;Crenarchaeota;
17       SILVA (only NR);Archaea;Crenarchaeota;Bathyarc...
18       SILVA (only NR);Archaea;Crenarchaeota;Methanom...
19       SILVA (only NR);Archaea;Crenarchaeota;Methanom...
20       SILVA (only NR);Archaea;Crenarchaeota;Methanom...
21       SILVA (only NR);Archaea;Crenarchaeota;Methanom...
22       SILVA (only NR);Archaea;Crenarchaeota;Nitrosos...
23       SILVA (only NR);Archaea;Crenarchaeota;Nitrosos...
24       SILVA (only NR);Archaea;Crenarchaeota;Nitrosos...
25       SILVA (only NR);Archaea;Crenarchaeota;Nitrosos...
26       SILVA (only NR);Archaea;Crenarchaeota;Nitrosos...
27       SILVA (only NR);Archaea;Crenarchaeota;Nitrosos...
28       SILVA (only NR);Archaea;Crenarchaeota;Nitrosos...
29       SILVA (only NR);Archaea;Crenarchaeota;Nitrosos...
                               ...
10231    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Oc...
10232    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Oc...
10233    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Oc...
10234    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Oc...
10235    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Oc...
10236    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Oc...
10237    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Oc...
10238    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Op...
10239    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...
10240    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...
10241    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...
10242    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...
10243    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...
10244    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...
10245    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...
10246    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...
10247    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...
10248    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...
10249    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...
10250    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...
10251    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...
10252    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...
10253    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pe...
10254    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pl...
10255    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pl...
10256    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pl...
10257    SILVA (only NR);Eukaryota;SAR;Stramenopiles;Pl...
10258    SILVA (only NR);Eukaryota;SAR;Stramenopiles;un...
10259                SILVA (only NR);Eukaryota;uncultured;
10260                                     SILVA (only NR);
Name: taxonomy, Length: 10261, dtype: object

In [ ]:
# remove everything before 7th semi-colon