In [2]:
#KSB# This is no longer being used right?
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import pandas as pd
import csv
import janitor
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

In [13]:
col_names = ["bug" + str(i) for i in range(1,51)]    
mock_df = pd.DataFrame(index=range(1,31),columns=range(1,51))
mock_df.columns = col_names

In [16]:
mock_df['sample'] = np.arange(len(mock_df))
mock_df['num_bugs'] = 6*[5, 10, 15, 25, 50]
mock_df['log_base'] = 5*[1] + 5*[2] + 5*[3] + 5*[4] + 5*[5]+ 5*[10]

In [17]:
mock_df

,bug1,bug2,bug3,bug4,bug5,bug6,bug7,bug8,bug9,bug10,...,bug44,bug45,bug46,bug47,bug48,bug49,bug50,sample,num_bugs,log_base
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,5,1
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10,1
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,15,1
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,25,1
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,50,1
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,5,2
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,10,2
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,15,2
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,25,2
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,50,2
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,5,3
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,10,3
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,15,3
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,25,3
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,50,3
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,5,4
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,10,4
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17,15,4
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18,25,4
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19,50,4
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20,5,5
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21,10,5
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22,15,5
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23,25,5
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24,50,5
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25,5,10
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26,10,10
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27,15,10
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28,25,10
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29,50,10

In [18]:
mock_df["log_base"][0+1]/

1

In [21]:
community_dict = {}
for i in range(len(mock_df)):
    bugs = [np.log(mock_df["log_base"][i+1])/np.log(j+1) for j in range(mock_df["num_bugs"][i+1])]
    community_dict[i] = (bugs)

/Users/danielle/miniconda2/envs/thesis_analysis/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in double_scalars
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/danielle/miniconda2/envs/thesis_analysis/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in double_scalars
  This is separate from the ipykernel package so we can avoid doing imports until

In [22]:
mock_communities = pd.DataFrame.from_dict(community_dict,orient='index')

In [23]:
mock_communities

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,inf,1.000000,0.630930,0.500000,0.430677,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,inf,1.000000,0.630930,0.500000,0.430677,0.386853,0.356207,0.333333,0.315465,0.301030,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,inf,1.000000,0.630930,0.500000,0.430677,0.386853,0.356207,0.333333,0.315465,0.301030,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,inf,1.000000,0.630930,0.500000,0.430677,0.386853,0.356207,0.333333,0.315465,0.301030,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,inf,1.000000,0.630930,0.500000,0.430677,0.386853,0.356207,0.333333,0.315465,0.301030,...,0.186652,0.185449,0.184289,0.183169,0.182088,0.181043,0.180031,0.179052,0.178104,0.177184
10,inf,1.584963,1.000000,0.792481,0.682606,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,inf,1.584963,1.000000,0.792481,0.682606,0.613147,0.564575,0.528321,0.500000,0.477121,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,inf,1.584963,1.000000,0.792481,0.682606,0.613147,0.564575,0.528321,0.500000,0.477121,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,inf,1.584963,1.000000,0.792481,0.682606,0.613147,0.564575,0.528321,0.500000,0.477121,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,inf,1.584963,1.000000,0.792481,0.682606,0.613147,0.564575,0.528321,0.500000,0.477121,...,0.295837,0.293930,0.292091,0.290316,0.288602,0.286946,0.285343,0.283791,0.282288,0.280830
15,inf,2.000000,1.261860,1.000000,0.861353,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,inf,2.000000,1.261860,1.000000,0.861353,0.773706,0.712414,0.666667,0.630930,0.602060,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,inf,2.000000,1.261860,1.000000,0.861353,0.773706,0.712414,0.666667,0.630930,0.602060,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,inf,2.000000,1.261860,1.000000,0.861353,0.773706,0.712414,0.666667,0.630930,0.602060,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,inf,2.000000,1.261860,1.000000,0.861353,0.773706,0.712414,0.666667,0.630930,0.602060,...,0.373305,0.370898,0.368578,0.366339,0.364176,0.362085,0.360063,0.358104,0.356207,0.354368
20,inf,2.321928,1.464974,1.160964,1.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,inf,2.321928,1.464974,1.160964,1.000000,0.898244,0.827087,0.773976,0.732487,0.698970,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,inf,2.321928,1.464974,1.160964,1.000000,0.898244,0.827087,0.773976,0.732487,0.698970,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,inf,2.321928,1.464974,1.160964,1.000000,0.898244,0.827087,0.773976,0.732487,0.698970,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,inf,2.321928,1.464974,1.160964,1.000000,0.898244,0.827087,0.773976,0.732487,0.698970,...,0.433393,0.430599,0.427905,0.425306,0.422795,0.420368,0.418020,0.415746,0.413544,0.411408
25,inf,3.321928,2.095903,1.660964,1.430677,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,inf,3.321928,2.095903,1.660964,1.430677,1.285097,1.183295,1.107309,1.047952,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,inf,3.321928,2.095903,1.660964,1.430677,1.285097,1.183295,1.107309,1.047952,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,inf,3.321928,2.095903,1.660964,1.430677,1.285097,1.183295,1.107309,1.047952,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,inf,3.321928,2.095903,1.660964,1.430677,1.285097,1.183295,1.107309,1.047952,1.000000,...,0.620046,0.616048,0.612194,0.608475,0.604883,0.601410,0.598051,0.594799,0.591647,0.588592

In [9]:
mock_communities.columns = col_names
mock_communities['sample'] = np.arange(len(mock_communities))
mock_communities['num_bugs'] = 3*[5, 10, 50]
mock_communities['log_base'] = [1, 1, 1, 2, 2, 2, 1.5, 1.5, 1.5]

In [14]:
mock_communities

,bug1,bug2,bug3,bug4,bug5,bug6,bug7,bug8,bug9,bug10,...,bug43,bug44,bug45,bug46,bug47,bug48,bug49,bug50,sample,num_bugs
0,1.0,1.0,1.00,1.000,1.0000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,5
1,1.0,1.0,1.00,1.000,1.0000,1.00000,1.000000,1.000000,1.000000,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10
2,1.0,1.0,1.00,1.000,1.0000,1.00000,1.000000,1.000000,1.000000,1.000000,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,2,50
3,1.0,2.0,4.00,8.000,16.0000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,5
4,1.0,2.0,4.00,8.000,16.0000,32.00000,64.000000,128.000000,256.000000,512.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,10
5,1.0,2.0,4.00,8.000,16.0000,32.00000,64.000000,128.000000,256.000000,512.000000,...,4.398047e+12,8.796093e+12,1.759219e+13,3.518437e+13,7.036874e+13,1.407375e+14,2.814750e+14,5.629500e+14,5,50
6,1.0,1.5,2.25,3.375,5.0625,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,5
7,1.0,1.5,2.25,3.375,5.0625,7.59375,11.390625,17.085938,25.628906,38.443359,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,10
8,1.0,1.5,2.25,3.375,5.0625,7.59375,11.390625,17.085938,25.628906,38.443359,...,2.487900e+07,3.731850e+07,5.597774e+07,8.396662e+07,1.259499e+08,1.889249e+08,2.833873e+08,4.250810e+08,8,50

In [13]:
mock_communities.to_csv("mock_communities.csv")